### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nabiloo19** [eichingertim/ProjectCreationAutomation#4]
This is what happened when I try to run the 'create command. Check the pics attahced'

create : The term 'create' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ create newTest public
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (create:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
![1](https://user-images.githubusercontent.com/45761185/66635976-ec56ea00-ec18-11e9-97f9-7465a4ff6ab9.png)

**Comment by nabiloo19** [comment]
![2](https://user-images.githubusercontent.com/45761185/66636061-1f997900-ec19-11e9-9eda-586bc99cdaaf.png)

**Comment by nabiloo19** [comment]
![3](https://user-images.githubusercontent.com/45761185/66636083-27591d80-ec19-11e9-9568-8dbce67600df.png)

**Comment by eichingertim** [comment]
Okay so in the environmental variables, you have to include the path to the batch-file, not to the full project. So you should add C:\Users\nabil\Documents\workspace\ProjectCreationAutomation\batch to your environmental variables instead of your current added path.

Second error: You must put a slash after "workspace" in your path in the python script.

**Comment by nabiloo19** [comment]
@eichingertim .. Thanks, it is resolved
